[[file:LICENSE][https://img.shields.io/github/license/Kyure-A/el-project.svg?style=flat-square]]
* el-project: Generate project skelton for Emacs Lisp
This project is inspired by [[https://github.com/fukamachi/cl-project][fukamachi/cl-project]].

** Installations
Push the following list to package-archives and install from package.el.
#+begin_src emacs-lisp
  ("kelpa" . "https://kelpa.kyre.moe/")
#+end_src

Alternatively, downloaders such as el-get, straight.el can be used.

** Usage

#+begin_src console
M-x el-project:make-project
#+end_src
When this command is executed, questions about the project are displayed interactively in the echo area. Simply follow this and enter the project information to complete the project template.

** Features
- Flexible templates

  el-project uses parameter embedding with [[https://github.com/magnars/s.el][s.el]]. Therefore, the output can be flexibly varied simply by changing the skelton (see "[[file:skelton/][cl-project/skelton]]"). 

- Multiple choices of package development tools.
  - [[https://github.com/emacs-eask/cli][Eask]]
  - [[https://github.com/cask/cask][Cask]]
  - [[https://github.com/conao3/keg.el][Keg]]

- Multiple choices of README formats
  - README.org
  - README.md

** License
This package is licensed by The GNU General Public License verson 3 or later. See [[file:LICENSE][LICENSE]].
